################################################################################
# https://gohugo.io/getting-started/configuration/#configure-build
################################################################################
_merge = "deep"
writeStats = true

[buildStats]
enable = true            # default is false
# disableClasses = false # default is false
# disableIDs = false     # default is false
# disableTags = false    # default is false

[[cachebusters]]
source = "assets/scss/.*\\.scss"
target = "css"

[[cachebusters]]
source = "assets/scss/*/.*\\.scss"
target = "css"

[[cachebusters]]
source = "assets/scss/*/*/.*\\.scss"
target = "css"

# [[cachebusters]]
# source = "assets/watching/hugo_stats\\.json"
# target = "css"

# [[cachebusters]]
# source = "(postcss|tailwind)\\.config\\.js"
# target = "css"

# [[cachebusters]]
# source = "assets/.*\\.(js|ts|jsx|tsx)"
# target = "js"

# [[cachebusters]]
# source = "assets/.*\\.(.*)$"
# target = "$1"
