################################################################################
# see https://gohugo.io/getting-started/configuration/
################################################################################
defaultContentLanguage = "en"
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
footnoteReturnLinkContents = "^"
languageCode = "en-us"
linenos = true
rssLimit = 10
summaryLength = 15
titleCaseStyle = "chicago"

##################################################################################
# error configuration
##################################################################################
ignoreErrors = []

##################################################################################
# hack: increasing timeout to prevent hugo from... timing out while recreating
# images. this is no more required for this website, because "we got RAM", but
# kept to find it when working on client projects.
# MUST be string, MUST contain digits and s for seconds, probably m for minutes
# (untested)
##################################################################################
timeout = "600s"

##################################################################################
# https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
# some configurations require different merge settings from the default
#
# Note that you don't need to be so verbose as in the default setup below;
# a `_merge` value higher up will be inherited if not set.
##################################################################################
[outputs]
_merge = 'deep'
[caches]
_merge = 'deep'
[module]
_merge = 'deep'
[build]
_merge = 'deep'
[markup]
_merge = 'deep'
[params]
_merge = 'deep'
[taxonomies]
_merge = 'shallow'
